apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  namespace: default
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: key1
  template:
    metadata:
      labels:
        app: key1
    spec:
      containers:
      - name: container1
        image: najamrizvi3/projd
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
spec: 
  selector:
    app: key1
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
  type: LoadBalancer
    
